"""Add column in users table for email notifications.

Revision ID: 971834834476
Revises: 7633d8fe5c8d
Create Date: 2021-03-28 00:14:01.716995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971834834476'
down_revision = '7633d8fe5c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=80), nullable=False))
    op.create_unique_constraint('user_email_key', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
